package com.MyAnimaLog.Veterinary.domain.shared.enums;

public enum VeterinaryEventType {
    VETERINARY_REGISTERED,
    VERIFICATION_SUBMITTED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    VERIFICATION_CORRECTION_REQUESTED,
    VETERINARY_SUSPENDED,
    VETERINARY_REACTIVATED,
    EMPLOYEE_INVITED,
    EMPLOYEE_JOINED,
    EMPLOYEE_ROLE_UPDATED,
    EMPLOYEE_DEACTIVATED,
    OWNERSHIP_TRANSFERRED,
    USER_LINKED,
    USER_UNLINKED,
    PET_SHARED_WITH_VETERINARY,
    PET_SHARE_REVOKED,
    SUBSCRIPTION_TRIAL_STARTED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_IN_GRACE,
    SUBSCRIPTION_EXPIRED,
    SUBSCRIPTION_RENEWED,
    PAYMENT_FAILED
}
